### ISSUE TITLE
nsp check on today's advisories inconsistent

### ISSUE THREAD

**Issue by ccsandrew** [nodesecurity/nsp#107]
We’ve been taking your product (nsp v2.3.3) for a test spin today.  To verify we added 3 items from your advisory list (as of 3:30pm on 5/11/2016) using 

npm install console-io@2.3.6 –save
npm install npm@2.15.0 –save
npm install node-uuid@1.4.0 –save 

Then running nsp check we got, no vulnerabilities found. 

 Is there something fundamental we are misunderstanding about your tool?

Then we found your demo site: 
https://github.com/nodesecurity/demo

So, in our test package we added

npm install marked@0.3.3

And we WERE able to see the security warnings.  

Your tool comes to us highly recommended, but we want to ensure we have total confidence in the output.

**Comment by evilpacket** [comment]
Thanks for taking the time to write this up and ask the question.

First item is  when I try and run npm i console-io@2.3.6 I get 
```
npm ERR! No compatible version found: console-io@2.3.6
```

When I pin to that version it doesn't come back with a positive result because it doesn't currently exist.

Also when I do a install of node-uuid@1.4.0 it puts in `"node-uuid": "^1.4.0"` in the package.json so when we do our comparison on the server side it says what is the latest version that matches that which would be 1.4.7 currently. If you pin that version to 1.4.0 (which is what would be installed in production, note we don't check your local installation, we check based on the package.json) it would properly report a vulnerability.

So --save defaulting to ^ semver is getting in the way of the results that you expect.

**Comment by ccsandrew** [comment]
Sorry the @2.3.6 was a typo, I meant to send you @2.6.3.

With regard to the others, you were correct, we neglected to pin down the package version like that in our demo.  

thanks for quick reply, I'll close the issue.
