### ISSUE TITLE
nsp check - showing vulnerabilites again after updating the modules

### ISSUE THREAD

**Issue by jetonk** [nodesecurity/nsp#121]
When you run: 
- nsp check,
And this finds the vulnerabilities, Ok I clean the vulnerable modules update them to newer version.

When I run again the nsp check, it shows me exactly the same output.

**Comment by nlf** [comment]
when you say you updated the modules, do you mean you used `npm install` to update them locally? or you changed your `package.json`/`npm-shrinkwrap.json`?

**Comment by jetonk** [comment]
I changed the version of the module in package.json, and then I executed npm install

**Comment by nlf** [comment]
what module, version and advisory specifically are you seeing this problem with?

**Comment by jetonk** [comment]
![screenshot from 2016-06-30 01-39-58](https://cloud.githubusercontent.com/assets/10130015/16472353/b214139c-3e63-11e6-9d41-2de7eb0acd0d.png)

**Comment by nlf** [comment]
can you share your package.json also?

**Comment by nlf** [comment]
if you can't share the whole thing, just the dependencies section is plenty

**Comment by jetonk** [comment]
` "dependencies": {
    "agenda": "^0.8.1",
    "body-parser": "^1.14.2",
    "chai": "^3.5.0",
    "chai-http": "^3.0.0",
    "compression": "^1.6.1",
    "dotenv": "^2.0.0",
    "express": "^4.14.0",
    "helmet": "^2.1.1",
    "mongoose": "^4.4.10",
    "morgan": "^1.7.0",
    "node-gcm": "^0.14.3",
    "nodemailer": "^2.1.0",
    "redis": "^2.6.0-1",
    "request": "^2.69.0",
    "sinon": "^1.17.3",
    "socketio": "^1.0.0",
    "stripe": "^4.6.0",
    "winston": "^2.2.0"
  },`

**Comment by nlf** [comment]
so the problem is that the `socket.io` module which `socketio` depends on uses static versions for its dependencies, rather than a range. the only way those dependencies would be satisfied is by using vulnerable versions, unfortunately.

you can see an example of that [here](https://github.com/socketio/socket.io/blob/master/package.json#L24)

so while you're using the newest version of your direct dependencies, the dependencies of those dependencies are old and vulnerable.

you *could* technically create a shrinkwrap file and change the version number for the subdependencies directly, but you'd be deviating from what the `socket.io` authors have said works correctly so that's very much at your own risk.

the better solution is to figure out where in the dependency chain the module that's preventing an updated module from installing is, and open an issue there requesting they update their dependencies and publish a new version.

one such issue is [this one](https://github.com/socketio/socket.io/issues/2591) which you can see links to [another issue for engine.io](https://github.com/socketio/engine.io/issues/401)

**Comment by guypod** [comment]
In the meantime, you should be able to apply a Snyk patch to protect against the issue. 
Per the advisory, we do have a patch for it: https://snyk.io/vuln/npm:engine.io-client:20160426

If you're using GitHub, you can do so through the GitHub integration: https://snyk.io/docs/github/
Or you can use the wizard: https://snyk.io/docs/using-snyk/#wizard

**Comment by jetonk** [comment]
@guypod snyk monitor now says that I'm having 0 vulnerabilities, but how much is trusted this report? Otherwise nsp is showing more vulns now.

**Comment by guypod** [comment]
There are a couple of vulns we held off on releasing till Monday as we're working through some technical issues. Not a common occurrence.

Otherwise you can trust it entirely.

**Comment by nlf** [comment]
the patch you linked to doesn't impact any of the advisories we reported.. maybe that was the wrong link?

**Comment by guypod** [comment]
Sorry, copy-paste mistake. That's what happens when you make a GitHub comment on a plane from your phone...

I was focusing on the negotiator vuln, here's the right link: https://snyk.io/vuln/npm:negotiator:20160616

You can see it show up on the socketio test page: https://snyk.io/test/npm/socketio

The ws issue (2 instances) is the one I mentioned is held up. A patch for it is about to be released early next week.

**Comment by KrishnaPuppala** [comment]
I also have the similar problem. I see the vulnerability though I updated the dependency. 
Here are the files attached. Could anyone provide me some good insights on this. 
![image](https://cloud.githubusercontent.com/assets/27292872/24917164/e2527430-1ea1-11e7-87e1-7e25bdd18f2e.png) 
project package.json file
![image](https://cloud.githubusercontent.com/assets/27292872/24917186/f8ad0aba-1ea1-11e7-9047-0406e702aa38.png)
Express package.json file 
![image](https://cloud.githubusercontent.com/assets/27292872/24917200/035093ce-1ea2-11e7-87b2-e846b7190fa3.png)
Accepts package.json file
![image](https://cloud.githubusercontent.com/assets/27292872/24917225/1bc49b08-1ea2-11e7-8580-a675b1f1623b.png)

**Comment by nlf** [comment]
Hi @KrishnaPuppala, did you see this behavior today?

We did recently have a package resolution bug that was resolved, and some packages are still playing catch up. I just created a project that depends on express `^4.14.0` as in your package.json, and a check returns no known vulnerabilities as of now.

Would you mind verifying if this is still an issue now?

**Comment by KrishnaPuppala** [comment]
Unfortunately, yes. 
It's still the same now.

**Comment by nlf** [comment]
Can you email the full dependencies portion of your package.json to contact@nodesecurity.io? I'll take a closer look and see if I can figure out what's going on.

**Comment by KrishnaPuppala** [comment]
Emailed it, thanks much!
