### ISSUE TITLE
Not all advisories showing up in nsp check

### ISSUE THREAD

**Issue by countergram** [nodesecurity/nsp#133]
I just started trying out `nsp check` and it does not appear to be flagging some of vulnerabilities from the most recent page of https://nodesecurity.io/advisories

```
mkdir testnsp
cd testnsp
npm init -y
npm install --save cookie-signature@1.0.3 mqtt@0.3.13 pivottable@1.4.0 c3@0.4.10 swagger-ui@2.1.0-M1 sanitize-html@1.4.2 ezseed-transmission@0.0.14 jws@2.x fuelux
nsp check -o summary
```

```
(+) 5 vulnerabilities found
 Name                  Installed   Patched     Path                                    More Info
 ezseed-transmission   0.0.14      >= 0.0.15   js@1.0.0 > ezseed-transmission@0.0.14   https://nodesecurity.io/advisories/114
 jws                   2.0.0       >=3.0.0     js@1.0.0 > jws@2.0.0                    https://nodesecurity.io/advisories/88
 mqtt                  0.3.13      >=1.0.0     js@1.0.0 > mqtt@0.3.13                  https://nodesecurity.io/advisories/140
 pivottable            1.6.3       >=2.0.0     js@1.0.0 > pivottable@1.6.3             https://nodesecurity.io/advisories/139
 swagger-ui            2.1.5       >=2.2.1     js@1.0.0 > swagger-ui@2.1.5             https://nodesecurity.io/advisories/126
```

It's missing cookie-signature, c3, sanitize-html, and fuelux. (node-krb5 is not here because it wouldn't compile.)

**Comment by wraithgar** [comment]
The reason that, for instance, cookie-signature does not show up in your results is because your package.json most likely says `^1.0.3` for the version, which means that if you were to do a plain `npm install` using that package the version that would install 1.0.6.  If you want to test having *exact* versions you will need to use a shrinkwrap file.  The `nsp check` only looks at your package.json and shrinkwrap.json files (the latter only if it exists)

**Comment by countergram** [comment]
Thanks for the explanation.
