### ISSUE TITLE
nsp check failing due to 404

### ISSUE THREAD

**Issue by timcosta** [nodesecurity/nsp#145]
```
$ nsp check
(+) Debug output: "404 page not found\n"
(+) Error: Got an invalid response from Node Security, please email the above debug output to support@nodesecurity.io
```

email was sent as well

**Comment by nlf** [comment]
i believe we responded to you via email, but this issue was due to an outage when our hosting provider was having some problems. we've since repaired the issue and modified our infrastructure a bit to hopefully prevent this particular failure from happening again in the future. i'm going to go ahead and close this one. thanks for letting us know!

**Comment by mjilugu** [comment]
Happening for me today.

**Comment by mjilugu** [comment]
(+) Debug output: "404 page not found\n"
(+) Error: Got an invalid response from Node Security, please email the above debug output to support@nodesecurity.io

**Comment by dragazor** [comment]
I'm now encountering the same problem. Please Help Us :)

**Comment by timcosta** [comment]
@nlf this is indeed happening again. Our automated CI build this morning failed.
