### ISSUE TITLE
nsp installation overwrites git hooks

### ISSUE THREAD

**Issue by philipb** [nodesecurity/nsp#194]
This is really a usage question, not an issue per se, unless you think it is.

I have added nsp to the devDependencies for a node project.  If I carry out a local install, like so:
```
npm install .
```
then the pre-commit hook (at .git/hooks/pre-commit) gets moved to .git/hooks/pre-commit.backup 
Is there a way to make nsp play nice with existing git hooks, or to integrate them into nsp?

**Comment by evilpacket** [comment]
Can you tell me what version of npm you are using as well as what version of nsp you are installing?

**Comment by evilpacket** [comment]
We did publish 2.8.1 last night that removed the devDeps from our shrinkwrap, that might fix the issue.

**Comment by philipb** [comment]
npm version 5.4.2
nsp version 2.8.0

I will try nsp 2.8.1 and report back.

**Comment by philipb** [comment]
Egad, that's fixed it!  My pre-commit hook is intact.

**Comment by evilpacket** [comment]
yes! that's great to hear. Sorry for the mixup.

**Comment by avbentem** [comment]
Just for search engines: 

We were not using Git hooks, but since we used `2.7.0^` early September the `pre-commit` and `pre-push` hooks were added, and not removed after upgrading to 2.8.1. In our case it also happened to make Git commit and push extremely slow (over 5 minutes for just a commit) on one specific Windows 7 machine. This was probably caused by our nested project structure which has `node_modules` in sub-folders (which might not have been excluded for the hooks), and/or by Git Bash being extremely slow on the affected machine anyway.

Manually removing the hooks solved that, but of course we were curious where they came from to start with. So, though I think the following refers to `git-validate`, just some text from the hooks, for those who might be looking for the source of the hooks as well:

```
# Get the exported path from the default login shell, and append it to the
# path from the environment. We ignore the stderr because there are
# potential errors and all we care about is the PATH.

# This section copied from github.com/dominictarr/JSON.sh and simplified a bit

# Search parsed JSON for a named script, return the script as a string

# Finds the appropriate commands to run for a project and runs them
```
