### ISSUE TITLE
Transitive dev dependencies are scanned

### ISSUE THREAD

**Issue by dlouwers** [nodesecurity/nsp#54]
Hi,

Some transitive dev dependencies in my project have known vulnerabilities (elasticsearch). However, these don't end up in production. Maybe these dependencies should be skipped full stop or it could be configurable for them to be skipped?

**Comment by reedloden** [comment]
:+1: for an option for this. I do care about security issues in dev dependencies, but I want to track them separately than ones that definitely do affect production. Having an option to skip dev dependencies would be very useful.

**Comment by nlf** [comment]
dev dependencies are actually not checked at all. sometimes children of dev dependencies can end up in your shrinkwrap due to how npm3 flattens the node_modules directory, however.

we've also recently made some major changes to how we generate the package tree that we check against. if you can reproduce this, feel free to reopen the issue.
