### ISSUE TITLE
Follow semver to not break API on point releases

### ISSUE THREAD

**Issue by ntotten** [nodesecurity/nsp#60]
We use nsp heavily in our projects and have noticed that there are often breaking changes between minor point releases. It would be ideal if you followed semver and broke only on major releases. For example, the output of the result changed from `2.0.1` to `2.0.2` which broke our CI. Additionally, it seems that the API you use may have changed and now older versions of nsp seem to return a 504 error when calling your api.

**Comment by latentflip** [comment]
Hey @ntotten we do try to follow semver as best as we can. That said, as far as CI integration goes, I guess we've been considering the exit code to be _the_ api, rather than the formatting of informative output text. Has something changed between 2.0.1 and 2.0.2 in that regard that we missed?

As for older versions breaking on the api, do you mean pre 2.0?

**Comment by evilpacket** [comment]
Closing as I believe this was answered. If it's not please reopen / comment.
