### ISSUE TITLE
Weird Semver error

### ISSUE THREAD

**Issue by KyleAMathews** [nodesecurity/nsp#70]
I'm getting this error when running `nsp audit-package`

```
/usr/lib/node_modules/nsp/node_modules/semver/semver.js:273
    throw new TypeError('Invalid Version: ' + version);
          ^
TypeError: Invalid Version: 3.11.01
    at new SemVer (/usr/lib/node_modules/nsp/node_modules/semver/semver.js:273:11)
    at compare (/usr/lib/node_modules/nsp/node_modules/semver/semver.js:460:10)
    at gte (/usr/lib/node_modules/nsp/node_modules/semver/semver.js:509:10)
    at cmp (/usr/lib/node_modules/nsp/node_modules/semver/semver.js:526:22)
    at Comparator.test (/usr/lib/node_modules/nsp/node_modules/semver/semver.js:599:10)
    at testSet (/usr/lib/node_modules/nsp/node_modules/semver/semver.js:922:17)
    at Range.test (/usr/lib/node_modules/nsp/node_modules/semver/semver.js:914:9)
    at satisfies (/usr/lib/node_modules/nsp/node_modules/semver/semver.js:935:16)
    at /usr/lib/node_modules/nsp/node_modules/semver/semver.js:941:12
    at Array.filter (native)
    at Function.maxSatisfying (/usr/lib/node_modules/nsp/node_modules/semver/semver.js:940:19)
    at /usr/lib/node_modules/nsp/lib/auditPackage.js:167:22
    at saved (/usr/lib/node_modules/nsp/node_modules/silent-npm-registry-client/node_modules/npm-registry-client/lib/get.js:142:7)
```

I don't have any packages with a version 3.11.01 and grepping for all package.jsons in my node_modules finds nothing either.

**Comment by evilpacket** [comment]
Do you have any modules that are set to * or latest?

**Comment by KyleAMathews** [comment]
no but I do have a couple of github repo links

**Comment by evilpacket** [comment]
Would you mind sending me your package file privately? baldwin@andyet.net <mailto:baldwin@andyet.net> and I could debug further? If not I'll dig in here after lunch  - We recently did some client updates because of versions changing out from under us (imagine that ha) so could be the source...

**Comment by KyleAMathews** [comment]
Sent

**Comment by evilpacket** [comment]
Can you update the client to nsp@1.0.1 ? I tried your package file against the latest version released yesterday and it completes successfully.

**Comment by KyleAMathews** [comment]
![screen shot 2015-03-12 at 2 30 31 pm](https://cloud.githubusercontent.com/assets/71047/6628639/65f9aa78-c8c4-11e4-89f3-4357c7102c39.png)

No luck...

**Comment by pdehaan** [comment]
I don't think that `3.11.01` is a valid semver value. I'm guessing it doesn't like the "0" prefix on the patch.

```js
var semver = require('semver');

var ver = '3.11.01';
console.log('"%s" is valid: %s', ver, semver.valid(ver)); // "3.11.01" is valid: null
```

Changing the `ver` to "3.11.1" says that the version _is_ valid though.

Probably doesn't help much, but you may want to run `npm shrinkwrap` or `npm ls` and search through the output and see if you can find the offending module (and maybe file a bug in the appropriate repo).

**Comment by evilpacket** [comment]
ok strange, I'm able to replicate the error now.

**Comment by evilpacket** [comment]
If I remove "codemirror": "^4.8.0", then it doesn't produce the error.

**Comment by KyleAMathews** [comment]
cool — that worked for me too. Conveniently too as I don't actually need codemirror anymore :)

How did you figure that out? I can't find any packages with a 3.11.01 version number.

**Comment by evilpacket** [comment]
brute force :)

There is a 3.11.1 version for code mirror though and so I think there is a bug in our code that determines which version is the max version to satisfy the semver string provided for a particular package.

We plan on a rewrite of the client VERY soon so might just end up fixing it because of that code, but thanks for the report and we'll continue to try and make it better.

**Comment by KyleAMathews** [comment]
:) haha, I know how that works.

Happy to help. Love the project!

**Comment by sverweij** [comment]
Seems this is what happens: auditPackage.js retrieves all versions for a package and asks server to get the "max satisfying". Trouble is that the collection of all versions can contain version numbers that don't satisfy semantic versioning (3.11.01 apparently, or - in my case 1.0.2beta for handlebars.js). Which makes semver barf. This is happening on line 167 - 169:
```javascript
                var ver = semver
                    .maxSatisfying(Object.keys(dependencyPkginfo.versions),
                                               dependencyVersion);

```

A short term solution could be to filter out the non semantic versions before passing them to maxSatisfying. like this:
```javascript
                var ver = semver
                    .maxSatisfying(Object.keys(dependencyPkginfo.versions)
                                                .filter(function(pVersion){
                                                    return semver.valid(pVersion);
                                                }),
                                               dependencyVersion);
```
I've tested this locally and it makes the error go away. 

It will introduce a new problem, though, when it is possible to get npm to install non-semantically versioned module versions (*--> is this scenario possible???*):
- package.json has version _^1.0.0_ for a module 
- the npm registry contains _1.0.1beta_ (or otherwise non-semver)
- ```npm install``` yields _1.0.1beta_ getting installed

_nsp_ would then have scanned 1.0.0, and not the _1.0.1beta_, which is actually used. And may contain malicious side-effects.

If this is indeed possible some creativity is still in order (otherwise I'm happy to provide a pull request over the weekend :-))

**Comment by evilpacket** [comment]
Thanks for this analysis! 

All of the semver functions do take a loose parameter as the last optional argument, if true they do allow matching against those types of values, so I think I could just turn loose on instead of filtering out versions to not be allowed. 

I just ran a test with that and it does seem to work for this particular case.

**Comment by pdehaan** [comment]
I'm guessing none of this would be solved by updating the **semver** dependency?
https://david-dm.org/nodesecurity/nsp

| DEPENDENCY	| REQUIRED	| STABLE	| LATEST
|----|----|----|----
| chalk		| ^0.5.1	| 1.0.0	| 1.0.0
| semver		| ^3.0.1	| 4.3.1	| 4.3.1

**Comment by evilpacket** [comment]
Something was broken the last time I tried to update and ran out of time debugging. I can certain try again or somebody can take a stab at it, however that being said we are going to be rewriting the entire client to not suck as much very soon :)

**Comment by evilpacket** [comment]
Closing this as we are deprecating the existing nsp client and moving to the requiresafe client
