### ISSUE TITLE
Path missing in NPM2 shrinkwrap check

### ISSUE THREAD

**Issue by betaorbust** [nodesecurity/nsp#70]
Currently getting 
```
(+) 3 vulnerabilities found
 Name        Installed   Patched   Path   More Info                             
 uglify-js   2.5.0       >=2.6.0          https://nodesecurity.io/advisories/48 
[... others]
```
(similar output with other reporters) 

None of the named packages are in the `package.json`, but they do show up in the `npm-shrinkwrap.json` file.

Note: this is NPM2 so I don't believe it's related to #44 
```
    "webpack": {
      "version": "1.12.4",
      "from": "webpack@1.12.4",
      "resolved": "http://artifacts.netflix.com/api/npm/npm-netflix/webpack/-/webpack-1.12.4.tgz",
      "dependencies": {
        //...
        "uglify-js": {
          "version": "2.5.0",
          "from": "uglify-js@>=2.5.0 <2.6.0",
          "resolved": "http://artifacts.netflix.com/api/npm/npm-netflix/uglify-js/-/uglify-js-2.5.0.tgz",
          "dependencies": {// ... }
        },
        //... 
      }
    },
```

**Comment by evilpacket** [comment]
Thanks for the issue. Paths are a tricky one. I'll try and detail out how they currently work and @nlf can clarify or maybe we can determine if this is a bug. 

This is something we had written up, but had not put anywhere just yet.

We receive a lot of questions as to how and which dependencies get checked for vulnerabilities. This document is intended to be the official representation of how that works and eliminate any confusion as to why or why not a dependency was checked.

nsp *always* requires a package.json file to check for vulnerabilities. An npm-shrinkwrap.json file is optional. The reason we require both, even when you provide a shrinkwrap, is because of the way npm flattens and/or dedupes dependencies in a shrinkwrap file. If we don't require your package.json we have no way of reliably determining the path to a vulnerable module.

## only a package.json available
When a package.json is processed we recursively look through all of the dependencies finding the latest published version that matches the provided semver string. We resolve this the same way npm would, and in theory what we end up checking will match exactly what npm would install.

### What is *not* checked
- devDependencies are not checked for vulnerabilities since they are not intended to be installed in production. 
- name spaced packages starting with an @ are currently not supported / checked 
- url's / git repositories are currently not supported / checked

## Both package.json and npm-shrinkwrap.json 
When both a package.json and npm-shrinkwrap.json are provided and processed the npm-shrinkwrap is used as the authority. 

The package.json is currently only used to attempt to identify proper paths, however if the npm-shrinkwrap contains dependencies (maybe from a git source) and that dependency is not in the package.json then a blank path will be provided in the output and identifying the source of the vulnerable module is up to you.

**Comment by nlf** [comment]
In addition to the above, there are likely some bugs (I've personally seen some duplicated entries because of the paths being calculated incorrectly). I'll be working on cleaning that code up and resolving some of those issues later this week.

**Comment by cristiandouce** [comment]
I'm dealing with the same issue. For example, I have recently removed a dependency from main to devDependency... and I still se both the libs highlighted as vulnerable... though no path, so I have *no idea* if there is something else I should be checking...

```bash

┌───────────────┬─────────────────────────────────────────┐
│               │ Regular Expression Denial of Service    │
├───────────────┼─────────────────────────────────────────┤
│ Name          │ semver                                  │
├───────────────┼─────────────────────────────────────────┤
│ Installed     │ 1.0.14                                  │
├───────────────┼─────────────────────────────────────────┤
│ Vulnerable    │ <4.3.2                                  │
├───────────────┼─────────────────────────────────────────┤
│ Patched       │ >=4.3.2                                 │
├───────────────┼─────────────────────────────────────────┤
│ Path          │                                         │
├───────────────┼─────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/31   │
└───────────────┴─────────────────────────────────────────┘
```

**Comment by thenano** [comment]
I'm having a weird issue where dependencies on shrinkwrap file are not being checked. I'm not sure if I need to pass a flag to the check command and didn't find it anywhere. Here's and example repo: https://github.com/thenano/nsp_test

here is what I get:
```
nsp_test (master) ∴ npm --version
3.5.2
```

```
nsp_test (master) ∴ nsp --version
2.2.0
```

```
nsp_test (master) ∴ nsp check
(+) No known vulnerabilities found
```

What am I doing wrong?

**Comment by nlf** [comment]
this is expected behavior, currently. we only check direct dependencies, not dev dependencies. since we evaluate both your package.json and your npm-shrinkwrap.json we're able to determine that you don't have any dependencies and so we return an empty result set.

we have it on our roadmap to also (optionally) scan dev dependencies.

**Comment by thenano** [comment]
ok, thanks for clarifying. Just to add context, the reason this is important for me is that I build an app that has a front end component, and gets packaged up with webpack. I list those dependencies as dev because they all get packaged up at build time, and I only need the server components as proper dependencies at runtime. So I would also like to know if I'm using a vulnerable version of jquery for example.

**Comment by nlf** [comment]
i'm going to close this issue for now. we have an internal tracking issue for checking dev dependencies (which is related to this issue) but i believe that any other bugs involving this issue are resolved.
