### ISSUE TITLE
nsp fails to report advisory 48 when uglify-js is a top-level dependency

### ISSUE THREAD

**Issue by sirbarrence** [nodesecurity/nsp#78]
In a project that uses `grunt-contrib-uglify@0.3.2`, nsp reports advisory 48 against `uglify-js@2.4.24` which is a dependency of `grunt-contrib-uglify`. But in a project with `uglify-js@2.4.24` as a top-level dependency in package.json, nsp reports "(+) No known vulnerabilities found". To reproduce:

```bash
mkdir grunt-proj
cd grunt-proj/
npm init # accept all defaults
npm install --save grunt-contrib-uglify@0.3.2
nsp check # reports vulnerability in "uglify-js@2.4.24"
cd ../
mkdir uglify-proj
cd uglify-proj/
npm init
npm install --save uglify-js@2.4.24
nsp check # reports "No known vulnerabilities found"
```

**Edit**: Expected behavior is to be warned of the vulnerability for both projects above, in case I wasn't clear.

**Comment by sirbarrence** [comment]
node 4.3.1
npm 2.14.12
nsp 2.2.0

**Comment by sirbarrence** [comment]
Am I fundamentally misunderstanding the tool? Is this user error? Any more information I can provide?

**Comment by evilpacket** [comment]
Thanks for the report. We just haven't had a chance to dig in and debug, we should be able to get to it this next week.

**Comment by latentflip** [comment]
I've figured out what's happening here, and I think ultimately it's a combination of npm's install process and version resolution being slightly confusing (I certainly got confused reproducing this); as well as us not explaining clearly how we handle `nsp check` when no shrinkwrap is provided.

Going to summarise here so hopefully we have a starting point for a piece of documentation somewhere about this:

Ultimately the question is: "How should we check for advisories against a semver _range_, when no shrinkwrap to narrow down the semver to a single version is provided?".

What we've been going with so far, is to check for advisories in `the most recent version that matches your semver` - i.e. the version of each dependency that would be installed if you ran a clean `npm install` right at the moment you ran `nsp check`. Therefore, if you have a different version currently _installed_ on your local machine, to the latest one on npm that matches your range, we'll be checking against the one on npm, rather than the version you have installed. 

The rationale is, that if you are not using a shrinkwrap, this is the version that would likely be installed if you went into production. 

---

### So why the differing result in this situation, it seems like the same advisory should be present?

The reason is how the npm versions are specified and resolved.

If you look at your package.json after running `npm install --save uglify-js@2.4.24`, you'll see that it the caret in the semver: `^2.4.24`, which basically means match any `2.something` version. As of right now the latest version that would match is `2.6.2` which is not known to be vulnerable at this time, so we report no vulns.

However, version `0.3.2` of `grunt-contrib-uglify` [specifies `uglify-js` as a dependency with `~2.4.0`](https://github.com/gruntjs/grunt-contrib-uglify/blob/v0.3.2/package.json#L30) rather than `^`. `~` operates differently to `^`, and effectively only increases the patch version, so `~2.4.0` matches the latest `2.4.x` version, which is currently `2.4.2` which _is_ vulnerable, so we report the vuln in that case.

> As an aside, the reason that `grunt-contrib-uglify@^0.3.2` itself resolves to `0.3.2` rather than say the latest version which is currently `0.11.1` is because when the version is a `^0.x.y` with the caret specifier, that will only resolve to the latest `0.x.something` version (tilde behaves differently on `0.x.y` version to `n.x.y` versions.

---

You can verify the above by:

1. Running `npm shrinkwrap` and then `nsp check` - this will now be checking against the installed versions which would fail in both cases
2. Install uglify-js with `npm install uglify-js@2.4.24 --save ---save-exact` which will save the exact semver to package.json, which would now be the latest version we match, and so will fail
3. Change the semver in package.json from `^2.4.24` to `~2.4.24` which will now be the same as when you install via `grunt-contrib-uglify` and so will also fail

---

Hope that all makes sense @sirbarrence, and thanks for using nsp :clap:! I'll let @evilpacket chip in if he has anything to add :)

**Comment by sirbarrence** [comment]
Thanks for the explanation. I think that makes sense. I do usually use a shrinkwrap file, but I don't think I was yet using one in the project where I noticed the top-level dependency issue. I'll verify tomorrow.

Yes, it would be helpful to have something about this in the readme and/or the CLI help.

Would it make sense to have a CLI switch that makes `nsp` check the versions that are currently installed in `node_modules` at that moment, regardless of package.json semvers? I now understand why that probably should not be the default mode, but as a new user kicking the tires on the tool, that's kindof what I expected. I don't know... Maybe such a switch would be pointless if the docs explain things a bit better to new users.

**Comment by sirbarrence** [comment]
Verified `nsp` works as expected when a shrinkwrap file is present:

```bash
cd uglify-proj/
npm init
npm install --save uglify-js@2.4.24
npm shrinkwrap
nsp check # reports vulnerability in "uglify-js@2.4.24"
```

**Comment by nlf** [comment]
sounds like it's safe to delete this? please do reopen if you're still having issues
