### ISSUE TITLE
Reliability

### ISSUE THREAD

**Issue by majgis** [nodesecurity/nsp#98]
We've found the nsp service to be unreliable, at least in regard to failing builds if there are security issues. We've reduced the checks to warnings.  Is there a time at which you expect the service to be more reliable?  I definitely appreciate all the work you have put into this service, and we want to rely on it more when the stability has improved.  Thank you for any information.

**Comment by nlf** [comment]
unreliable in what way? are you getting errors from the client? have you sent us those errors so we can investigate? we find new edge cases in the way we process `package.json` and `npm-shrinkwrap.json` files every day, so the more information you can provide us the better.

**Comment by majgis** [comment]
This one occurred today, after the last notice on twitter:
(+) Debug output: "<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n\n"
(+) Error: Got an invalid response from Node Security, please email the above debug output to support@nodesecurity.io

but the service is back up now.

And on last Thursday we emailed an issue.

So at least 3 outages in 5 days.  Just curious it is a transitional period behind the scenes.

**Comment by nlf** [comment]
unfortunately, it is. the servers we're currently running everything for nsp on have been a bit glitchy the last few weeks. we've been pushing hard on code so i haven't had time to address that concern yet.

i do have plans to upgrade what we're running on in the very near future though, and it should take care of these issues

**Comment by majgis** [comment]
I appreciate the info.  I'll dial our settings back to failing builds when things have stabilized.  Thank you.

**Comment by ernoaapa** [comment]
Yeah same issues here. Would be great if you ping here when it's ok to enable nsp check. Cheers!

**Comment by evilpacket** [comment]
So to clarify, @nlf and team are doing a lot of work behind the scenes to make this all go.

A little background for comparison. The first version of nsp wouldn't even finish running a check if a package had something like 1400 dependencies. Since then we've rebuilt the client and the api to make sure that happens in seconds, not hours or forever. (I wrote some really bad code way back when). So we've come a long way performance wise. 

We've seen a huge uptick in nsp adoption. We currently process about 30k nsp checks per day. That number isn't going to go down either, We're adding in the ability for push button addition of nsp monitoring to GitHub repositories for continued monitoring and want a stable and reliable service just as much as you do.

We've added a caching layer to alleviate some database load and have been doing query and data optimizations to ensure checks continue to stay fast.

Finally and the biggest reason for the instability is our current containerization infrastructure. Our ops team is using some shared infrastructure with another project for cost savings and we're moving off of that and will be using kubernetes so our freak'n load balancer can stop saying there is no servers to handle the requests, when there really is.

**Comment by majgis** [comment]
https://twitter.com/nodesecurity/status/728366662211211264
Did this change address this issue?  Can it be closed?

**Comment by ernoaapa** [comment]
Haven't seen this issue anymore. Thanks for all you guys do!

**Comment by nlf** [comment]
Yes! That tweet was is migrating to new infrastructure. I won't guarantee that there won't be any more hiccups as we scale, but things are greatly improved right now. Closing this
